### ISSUE TITLE
Mac 32-bit binaries are missing in v1.1.0

### ISSUE THREAD

**Issue by nwolek** [nwolek/LowkeyNW#14]
Some people reported the problem on [the Cycling'74 page here](https://cycling74.com/toolbox/lowkeynw-max-package/#post-354738).

Looks like the Cmake flags are not set to compile Universal Binary. Found some [discussion of Cmake settings here](https://cmake.org/pipermail/cmake/2010-May/036707.html).

Tried setting `CMAKE_OSX_ARCHITECTURES` manually in `CMakeCache.txt` within the build folder, but it complains there is `No rule to make target` and exits the build with code 2.

Something similar happens when I tried to change the system architecture in Xcode.

Because of the choreography between `max-sdk-core` and this package, I will likely need @tap to collaborate on a solution.

**Comment by tap** [comment]
Thanks.  Looking into it now...

**Comment by tap** [comment]
Should be good now.  Please double-check.  Thanks again!

**Comment by nwolek** [comment]
Working here in 32- and 64-bit modes. Thanks @tap! I am tagging the release as v1.1.1 and sending the update to Andrew.
